apiVersion: v1
kind: Pod
metadata:
    name: {{ .Values.nameprefix}}-my-app
spec:
    containers:
        - name: main
          image: alexcollinsintuit/my-app:v1
          imagePullPolicy: IfNotPresent
          env:
              - name: GREETING
                value: "{{ .Values.greeting }}"
